### ISSUE TITLE
Updating to 0.2.0 in dependencies still downloads 0.1.0 code

### ISSUE THREAD

**Issue by sic-f** [DanToml/Bees#10]
Might just be me, but after updating to `{:bees, "~> 0.2.0"}` in the `mix.exs` file in a Phoenix project, and running `mix deps.get`, it downloads *Bees 0.2.0*

But when looking in the `deps` folder in `bees`, the code is still the old one (`0.1.0`), resulting calls to the new endpoints in `0.2.0` (e.g. `Bees.Venue.explore/8`) to cause an exception since that endpoint is not present in the package's code

**Comment by DanToml** [comment]
@sic-f interesting.... :confused:

**Comment by DanToml** [comment]
I'll take a look into this, I may have messed up doing the release (I haven't been using elixir much lately).

**Comment by sic-f** [comment]
@DanToml it's ok, I'm also trying to know why it is doing this. Might just be in my machine/setup.

Does this have anything to do with it:

`lib/bees.ex`
```
defmodule Bees do
  @version "0.1.0"
  def version, do: @version
end
```

or is this just purely for displaying the version in the command line?

**Comment by DanToml** [comment]
@sic-f That is... probably the reason. For the sake of sanity checking and getting out some other fixes, I just published 0.3.0

**Comment by sic-f** [comment]
@DanToml confirmed that this is fixed. Newly added endpoints are now present in the codebase and are working 👍

**Comment by DanToml** [comment]
@sic-f Yay! 🎉
