### ISSUE TITLE
Incompatible with Phoenix 1.3

### ISSUE THREAD

**Issue by sic-f** [DanToml/Bees#5]
Giving error **Failed to use "poison" (version 3.1.0)** when using **Phoenix 1.3** when doing `mix deps.get`

Worked fine when using **Phoenix 1.2**

Screenshot:
<img width="1263" alt="mix deps.get" src="https://user-images.githubusercontent.com/17798988/32876565-66d64550-cad8-11e7-9b3a-8bfb2377d265.png">

**Comment by DanToml** [comment]
This is fixed on master, I’ll try and get a release out today

**Comment by DanToml** [comment]
bees 0.2.0 should be live now :+1:
